services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000/api

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    env_file:
      - ./.env

  database:
    build: ./database
    ports:
      - "3306:3306"
    volumes:
      - crypto_data:/var/lib/mysql
    env_file:
      - ./.env

volumes:
  crypto_data: